class OttPlatFormExc{

public static void main(String[] abx){
	HotStar star=new HotStar();
	String movieName[] = {"MAJESTIC","NINAGOSKARA","KITTY","KARIYA","LAALI HAADU","NEENADERE ISTA","KUSHALAVE KSHAMAVE","NAMMA PRITHIYA RAMU","LANKESH PATRIKE","ANNAVRU","DHARMA","DARSHAN","BHAGAWAN","KALASIPALYA","SARDARA","AYYA","SHASTRI","SWAMY","MANDYA","SUNTARAGALI","DATTHA","THANGIGAGI","BHOOPATHI","SNEHANA PREETHINA","ANATHARU"};
	star.getMovies(movieName);
}

}